# Generated by Django 4.2.4 on 2023-08-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Страва',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('назва', models.CharField(max_length=200)),
                ('опис', models.TextField()),
                ('ціна', models.DecimalField(decimal_places=2, max_digits=5)),
                ('дата_додавання', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
